# [[file:../../../config/nix.org::*Emacs Packages][Emacs Packages:1]]
epkgs: [
  epkgs.all-the-icons
  epkgs.agda2-mode
  epkgs.auctex
  epkgs.catppuccin-theme
  epkgs.company
  epkgs.company-box
  epkgs.company-solidity
  epkgs.counsel
  epkgs.centaur-tabs
  epkgs.dash
  epkgs.dashboard
  epkgs.doom-themes
  epkgs.doom-modeline
  epkgs.indent-bars
  epkgs.irony
  epkgs.elfeed
  epkgs.elfeed-org
  epkgs.elfeed-tube
  epkgs.elfeed-tube-mpv
  epkgs.elpher
  epkgs.ement
  epkgs.emmet-mode
  epkgs.emms
  epkgs.engrave-faces
  epkgs.enwc
  epkgs.evil
  epkgs.evil-collection
  epkgs.evil-commentary
  epkgs.evil-org
  epkgs.f
  epkgs.flycheck
  epkgs.geiser
  epkgs.geiser-chez
  epkgs.general
  epkgs.git-gutter
  epkgs.gptel
  epkgs.gruvbox-theme
  epkgs.haskell-mode
  epkgs.htmlize
  epkgs.idris-mode
  epkgs.irony-eldoc
  epkgs.ivy
  epkgs.ivy-posframe
  epkgs.latex-preview-pane
  epkgs.lsp-ivy
  epkgs.lsp-mode
  epkgs.lsp-haskell
  epkgs.lyrics-fetcher
  epkgs.mastodon
  epkgs.magit
  epkgs.magit-delta
  epkgs.mu4e
  epkgs.mixed-pitch
  epkgs.minuet
  epkgs.nix-mode
  epkgs.ox-rss
  epkgs.ob-nix
  epkgs.org-contrib
  epkgs.org-ql
  epkgs.org-super-agenda
  epkgs.org-fragtog
  epkgs.org-journal
  epkgs.org-modern
  epkgs.org-roam
  epkgs.org-roam-ui
  epkgs.page-break-lines
  epkgs.password-store
  epkgs.pdf-tools
  epkgs.pinentry
  epkgs.platformio-mode
  epkgs.projectile
  epkgs.rustic
  epkgs.s
  epkgs.solaire-mode
  epkgs.scad-mode
  epkgs.simple-httpd
  epkgs.solidity-flycheck
  epkgs.solidity-mode
  epkgs.sudo-edit
  epkgs.treemacs
  epkgs.treemacs-evil
  epkgs.treemacs-magit
  epkgs.treemacs-projectile
  epkgs.treemacs-all-the-icons
  epkgs.all-the-icons-ivy-rich
  epkgs.treesit-auto
  epkgs.typescript-mode
  epkgs.use-package
  epkgs.vterm
  epkgs.wgrep
  epkgs.web-mode
  epkgs.websocket
  epkgs.which-key
  epkgs.writegood-mode
  epkgs.writeroom-mode
  epkgs.yaml-mode
  epkgs.yasnippet
  epkgs.yasnippet-snippets
]
# Emacs Packages:1 ends here
